name: Actionbot
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/**.yml'
      - '.github/workflows/**.yaml'
      - '.github/actions/**.yml'
      - '.github/actions/**.yaml'
      
jobs:
  actionbot:
    permissions:
      contents: write
      checks: write
      id-token: write
    uses: Contrast-Security-Inc/labs-actions/.github/workflows/actionbot-allow-main.yml@ca4dfbe26230f5ba83efe63cc289d1460dab193d
    secrets:
      GH_API_ACCESS_TOKEN: ${{ secrets.GH_API_ACCESS_TOKEN }}
