name: "Actionbot - Allow Policy"
description: "This workflow runs the Actionbot with an allow policy to check for violations in the codebase."
on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  enforce-allow-policy:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 1

      - name: Run Actionbot - Allow Policy
        id: Actionbot
        uses: Contrast-Security-OSS/actionbot@d42e6bf0847e7b56d769421c54b847e4b28a8dfc
        with:
          policy: 'allow'
          policy-url: 'https://github.com/Contrast-Security-Inc/labs-action-policy/blob/main/allow_policy.json' # Contrast-Security-Inc policy
          github-token: ${{ secrets.GH_API_ACCESS_TOKEN }}
          fail-if-violations: 'true'

      - name: Respond to action policy violations
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        if: steps.Actionbot.outputs.violations
        with:
          github-token: ${{ secrets.GH_API_ACCESS_TOKEN }}
          script: |
            const violations = JSON.parse(steps.actionbot.outputs.violations);
            console.log('Violations found:', violations);