name: 'Auto Assign PR'
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  add-owner:
    runs-on: ubuntu-latest
    steps:
      - name: run
        uses: kentaro-m/auto-assign-action@3e986bf9c274729de0d85191da42484917883328  #v1.2.5
        with:
          configuration-path: ".github/auto_assign_pr.yml"
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
